### ISSUE TITLE
SSHKey not saved in the kv store

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/www-mastodon#22]
![image](https://user-images.githubusercontent.com/64129/203864990-9e240320-1021-4928-a54d-bf25e2794d7e.png)

i loaded the mnemonics again, the sshkey didn't show back

**Comment by mohamedamer453** [comment]
The mnemonics are now stored in kv store. 

as seen below when i entered my ssh key it started storing it and when i removed the mnemonics and reloaded the page then i entered my mnemonics again it loaded my key again without any issues.

[Get Mastodon (4).webm](https://user-images.githubusercontent.com/101194226/204539296-296d9168-3b70-4bf8-99e5-902a3ba4965d.webm)

however the problem is that when it's loaded it then starts to store it again, is this normal behavior to store the key every time it's loaded from the mnemonics?
