### ISSUE TITLE
UX: The discount needs to be explained better on the weblet

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/www-mastodon#80]

**Comment by xmonader** [comment]
@samtaggart please provide the text

**Comment by samtaggart** [comment]
@xmonader I first need to understand some things, please join the call tomorrow 10am CET

**Comment by samtaggart** [comment]
I would suggest this:

Based on your specifications, the standard deployment cost is XX USD/month.
Because you have X TFT in your TF Chain Wallet, your cost is XX USD/month. [Learn more](https://library.threefold.me/info/threefold#/cloud/threefold__pricing?id=discount-levels).

This way, we are speaking directly to each person based on the number of TFT in their wallet. It pulls in their discount level automatically.

What do you think? @xmonader @AhmedHanafy725 

Otherwise we can also go with something like this:

Based on your specifications, the standard deployment cost is XX USD/month.
Unlock up to a 60% discount by holding TFT in your TF Chain Wallet. [Learn more](https://library.threefold.me/info/threefold#/cloud/threefold__pricing?id=discount-levels).

But this is less cool.

**Comment by samtaggart** [comment]
I think this is being solved here no? https://github.com/threefoldtech/www-mastodon/issues/118

**Comment by mohamedamer453** [comment]
Verified in https://github.com/threefoldtech/www-mastodon/issues/118#issuecomment-1356739251
